[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

[phases.setup.cache]
paths = ["node_modules", ".next/cache"]

[phases.install.cache]
paths = ["node_modules"]

[phases.build.cache]
paths = [".next"] 
